export const equipment = [
    {name:"assisted"},
    {name:"band"},
    {name:"barbell"},
    {name:"body weight"},
    {name:"bosu ball"},
    {name:"cable"},
    {name:"dumbbell"},
    {name:"elliptical machine"},
    {name:"ez barbell"},
    {name:"hammer"},
    {name:"kettlebell"},
    {name:"leverage machine"},
    {name:"medicine ball"},
    {name:"olympic barbell"},
    {name:"resistance band"},
    {name:"roller"},
    {name:"skierg machine"},
    {name:"sled machine"},
    {name:"smith machine"},
    {name:"stability ball"},
    {name:"stationary bike"},
    {name:"stepmill machine"},
    {name:"tire"},
    {name:"trap bar"},
    {name:"upper body ergometer"},
    {name:"weighted"},
    {name:"wheel roller"}
]
